run:
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 100

issues:
  new: true
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"

linters:
  disable-all: true
  enable:
    - gci
    - gofmt
    - golint
    - misspell
    - govet
    - goconst
    - deadcode
    - gocyclo
    - staticcheck
    - errcheck

output:
  print-issued-lines: true
  print-linter-name: true
