---
apiVersion: v1
kind: Service
metadata:
  name: file-server
spec:
  selector:
    app: dragonfly
    component: file-server
  type: ClusterIP
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: file-server
spec:
  serviceName: file-server
  selector:
    matchLabels:
      app: dragonfly
      component: file-server
  replicas: 1
  template:
    metadata:
      labels:
        app: dragonfly
        component: file-server
    spec:
      containers:
      - name: file-server
        image: dragonflyoss/file-server:latest 
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 80
