name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: '0'

      - name: Golangci lint
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee
        with:
          version: v2.7

      - name: Markdown lint
        uses: docker://avtodev/markdown-lint:v1
        with:
          config: '.markdownlint.yml'
          args: '**/*.md'
